
# This file is automatically generated, you probably don't want to edit this

SemGuiOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SemGuiOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            latentVars = list(),
            modelSpec = "{\"nodes\":[],\"edges\":[]}",
            estimator = "ml",
            missing = "fiml",
            identification = "variance",
            testStats = TRUE,
            ci = FALSE,
            ciWidth = 95,
            std = FALSE,
            hideResiduals = TRUE,
            showParamTable = FALSE,
            fitChiSq = TRUE,
            fitCFI = TRUE,
            fitTLI = TRUE,
            fitSRMR = FALSE,
            fitRMSEA = TRUE,
            fitAIC = FALSE,
            fitBIC = FALSE,
            modIndices = FALSE,
            modIndicesThreshold = 3,
            residCov = FALSE,
            residCovThreshold = 0.1,
            showSyntax = FALSE, ...) {

            super$initialize(
                package="semgui",
                name="SemGui",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..latentVars <- jmvcore::OptionArray$new(
                "latentVars",
                latentVars,
                default=list(),
                template=jmvcore::OptionString$new(
                    "latentVars",
                    NULL,
                    default="F1"))
            private$..modelSpec <- jmvcore::OptionString$new(
                "modelSpec",
                modelSpec,
                default="{\"nodes\":[],\"edges\":[]}",
                hidden=TRUE)
            private$..estimator <- jmvcore::OptionList$new(
                "estimator",
                estimator,
                options=list(
                    "ml",
                    "mlr",
                    "mlm",
                    "wlsmv",
                    "uls"),
                default="ml")
            private$..missing <- jmvcore::OptionList$new(
                "missing",
                missing,
                options=list(
                    "fiml",
                    "listwise"),
                default="fiml")
            private$..identification <- jmvcore::OptionList$new(
                "identification",
                identification,
                options=list(
                    "variance",
                    "marker"),
                default="variance")
            private$..testStats <- jmvcore::OptionBool$new(
                "testStats",
                testStats,
                default=TRUE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..std <- jmvcore::OptionBool$new(
                "std",
                std,
                default=FALSE)
            private$..hideResiduals <- jmvcore::OptionBool$new(
                "hideResiduals",
                hideResiduals,
                default=TRUE)
            private$..showParamTable <- jmvcore::OptionBool$new(
                "showParamTable",
                showParamTable,
                default=FALSE)
            private$..fitChiSq <- jmvcore::OptionBool$new(
                "fitChiSq",
                fitChiSq,
                default=TRUE)
            private$..fitCFI <- jmvcore::OptionBool$new(
                "fitCFI",
                fitCFI,
                default=TRUE)
            private$..fitTLI <- jmvcore::OptionBool$new(
                "fitTLI",
                fitTLI,
                default=TRUE)
            private$..fitSRMR <- jmvcore::OptionBool$new(
                "fitSRMR",
                fitSRMR,
                default=FALSE)
            private$..fitRMSEA <- jmvcore::OptionBool$new(
                "fitRMSEA",
                fitRMSEA,
                default=TRUE)
            private$..fitAIC <- jmvcore::OptionBool$new(
                "fitAIC",
                fitAIC,
                default=FALSE)
            private$..fitBIC <- jmvcore::OptionBool$new(
                "fitBIC",
                fitBIC,
                default=FALSE)
            private$..modIndices <- jmvcore::OptionBool$new(
                "modIndices",
                modIndices,
                default=FALSE)
            private$..modIndicesThreshold <- jmvcore::OptionNumber$new(
                "modIndicesThreshold",
                modIndicesThreshold,
                default=3,
                min=0)
            private$..residCov <- jmvcore::OptionBool$new(
                "residCov",
                residCov,
                default=FALSE)
            private$..residCovThreshold <- jmvcore::OptionNumber$new(
                "residCovThreshold",
                residCovThreshold,
                default=0.1,
                min=0)
            private$..showSyntax <- jmvcore::OptionBool$new(
                "showSyntax",
                showSyntax,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..latentVars)
            self$.addOption(private$..modelSpec)
            self$.addOption(private$..estimator)
            self$.addOption(private$..missing)
            self$.addOption(private$..identification)
            self$.addOption(private$..testStats)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..std)
            self$.addOption(private$..hideResiduals)
            self$.addOption(private$..showParamTable)
            self$.addOption(private$..fitChiSq)
            self$.addOption(private$..fitCFI)
            self$.addOption(private$..fitTLI)
            self$.addOption(private$..fitSRMR)
            self$.addOption(private$..fitRMSEA)
            self$.addOption(private$..fitAIC)
            self$.addOption(private$..fitBIC)
            self$.addOption(private$..modIndices)
            self$.addOption(private$..modIndicesThreshold)
            self$.addOption(private$..residCov)
            self$.addOption(private$..residCovThreshold)
            self$.addOption(private$..showSyntax)
        }),
    active = list(
        vars = function() private$..vars$value,
        latentVars = function() private$..latentVars$value,
        modelSpec = function() private$..modelSpec$value,
        estimator = function() private$..estimator$value,
        missing = function() private$..missing$value,
        identification = function() private$..identification$value,
        testStats = function() private$..testStats$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        std = function() private$..std$value,
        hideResiduals = function() private$..hideResiduals$value,
        showParamTable = function() private$..showParamTable$value,
        fitChiSq = function() private$..fitChiSq$value,
        fitCFI = function() private$..fitCFI$value,
        fitTLI = function() private$..fitTLI$value,
        fitSRMR = function() private$..fitSRMR$value,
        fitRMSEA = function() private$..fitRMSEA$value,
        fitAIC = function() private$..fitAIC$value,
        fitBIC = function() private$..fitBIC$value,
        modIndices = function() private$..modIndices$value,
        modIndicesThreshold = function() private$..modIndicesThreshold$value,
        residCov = function() private$..residCov$value,
        residCovThreshold = function() private$..residCovThreshold$value,
        showSyntax = function() private$..showSyntax$value),
    private = list(
        ..vars = NA,
        ..latentVars = NA,
        ..modelSpec = NA,
        ..estimator = NA,
        ..missing = NA,
        ..identification = NA,
        ..testStats = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..std = NA,
        ..hideResiduals = NA,
        ..showParamTable = NA,
        ..fitChiSq = NA,
        ..fitCFI = NA,
        ..fitTLI = NA,
        ..fitSRMR = NA,
        ..fitRMSEA = NA,
        ..fitAIC = NA,
        ..fitBIC = NA,
        ..modIndices = NA,
        ..modIndicesThreshold = NA,
        ..residCov = NA,
        ..residCovThreshold = NA,
        ..showSyntax = NA)
)

SemGuiResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SemGuiResults",
    inherit = jmvcore::Group,
    active = list(
        diagram = function() private$.items[["diagram"]],
        modelFit = function() private$.items[["modelFit"]],
        parameters = function() private$.items[["parameters"]],
        modIndices = function() private$.items[["modIndices"]],
        residCov = function() private$.items[["residCov"]],
        lavaanCode = function() private$.items[["lavaanCode"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Graphical SEM")
            self$add(jmvcore::Html$new(
                options=options,
                name="diagram",
                title="Path Diagram Editor",
                clearWith=list()))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    test = function() private$.items[["test"]],
                    fitMeasures = function() private$.items[["fitMeasures"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="modelFit",
                            title="Model Fit")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="test",
                            title="Fit tests",
                            rows=1,
                            visible="(fitChiSq)",
                            clearWith=list(
                                "vars",
                                "modelSpec",
                                "estimator",
                                "missing"),
                            columns=list(
                                list(
                                    `name`="chi", 
                                    `title`="\u03C7\u00B2", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="fitMeasures",
                            title="Fit indices",
                            rows=1,
                            visible="(fitCFI || fitTLI || fitSRMR || fitRMSEA || fitAIC || fitBIC)",
                            clearWith=list(
                                "vars",
                                "modelSpec",
                                "estimator",
                                "missing"),
                            columns=list(
                                list(
                                    `name`="cfi", 
                                    `title`="CFI", 
                                    `type`="number", 
                                    `visible`="(fitCFI)"),
                                list(
                                    `name`="tli", 
                                    `title`="TLI", 
                                    `type`="number", 
                                    `visible`="(fitTLI)"),
                                list(
                                    `name`="srmr", 
                                    `title`="SRMR", 
                                    `type`="number", 
                                    `visible`="(fitSRMR)"),
                                list(
                                    `name`="rmsea", 
                                    `title`="RMSEA", 
                                    `type`="number", 
                                    `visible`="(fitRMSEA)"),
                                list(
                                    `name`="rmseaLower", 
                                    `title`="Lower", 
                                    `type`="number", 
                                    `superTitle`="RMSEA 90% CI", 
                                    `visible`="(fitRMSEA)"),
                                list(
                                    `name`="rmseaUpper", 
                                    `title`="Upper", 
                                    `type`="number", 
                                    `superTitle`="RMSEA 90% CI", 
                                    `visible`="(fitRMSEA)"),
                                list(
                                    `name`="aic", 
                                    `title`="AIC", 
                                    `type`="number", 
                                    `visible`="(fitAIC)"),
                                list(
                                    `name`="bic", 
                                    `title`="BIC", 
                                    `type`="number", 
                                    `visible`="(fitBIC)"))))}))$new(options=options))
            self$add(jmvcore::Table$new(
                options=options,
                name="parameters",
                title="Parameter Estimates",
                visible="(showParamTable)",
                rows=0,
                clearWith=list(
                    "vars",
                    "modelSpec",
                    "estimator",
                    "missing",
                    "std",
                    "ci",
                    "ciWidth",
                    "hideResiduals"),
                columns=list(
                    list(
                        `name`="label", 
                        `title`="Label", 
                        `type`="text"),
                    list(
                        `name`="lhs", 
                        `title`="LHS", 
                        `type`="text"),
                    list(
                        `name`="op", 
                        `title`="Type", 
                        `type`="text"),
                    list(
                        `name`="rhs", 
                        `title`="RHS", 
                        `type`="text"),
                    list(
                        `name`="est", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(testStats)"),
                    list(
                        `name`="z", 
                        `title`="z", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(testStats)"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(testStats)"),
                    list(
                        `name`="ciLower", 
                        `title`="Lower (95%CI)", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(ci)"),
                    list(
                        `name`="ciUpper", 
                        `title`="Upper (95%CI)", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(ci)"),
                    list(
                        `name`="stdAll", 
                        `title`="Std. Estimate", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(std)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="modIndices",
                title="Modification Indices",
                visible="(modIndices)",
                rows=0,
                clearWith=list(
                    "vars",
                    "modelSpec",
                    "estimator",
                    "missing"),
                columns=list(
                    list(
                        `name`="lhs", 
                        `title`="LHS", 
                        `type`="text"),
                    list(
                        `name`="op", 
                        `title`="Type", 
                        `type`="text"),
                    list(
                        `name`="rhs", 
                        `title`="RHS", 
                        `type`="text"),
                    list(
                        `name`="mi", 
                        `title`="MI", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="epc", 
                        `title`="EPC", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="residCov",
                title="Residual Covariances",
                visible="(residCov)",
                rows=0,
                clearWith=list(
                    "vars",
                    "modelSpec",
                    "estimator",
                    "missing"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="lavaanCode",
                title="lavaan Model Syntax",
                visible="(showSyntax)",
                clearWith=list(
                    "vars",
                    "modelSpec")))}))

SemGuiBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SemGuiBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "semgui",
                name = "SemGui",
                version = c(1,0,0),
                options = options,
                results = SemGuiResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Graphical SEM
#'
#' A graphical user interface for structural equation modeling. Supports CFA, 
#' path models, full SEM, higher-order factors, and bifactor models.
#' @param data .
#' @param vars .
#' @param latentVars .
#' @param modelSpec .
#' @param estimator .
#' @param missing .
#' @param identification .
#' @param testStats .
#' @param ci .
#' @param ciWidth .
#' @param std .
#' @param hideResiduals .
#' @param showParamTable .
#' @param fitChiSq .
#' @param fitCFI .
#' @param fitTLI .
#' @param fitSRMR .
#' @param fitRMSEA .
#' @param fitAIC .
#' @param fitBIC .
#' @param modIndices .
#' @param modIndicesThreshold .
#' @param residCov .
#' @param residCovThreshold .
#' @param showSyntax .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$diagram} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelFit$test} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modelFit$fitMeasures} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$parameters} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modIndices} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$residCov} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$lavaanCode} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$parameters$asDF}
#'
#' \code{as.data.frame(results$parameters)}
#'
#' @export
SemGui <- function(
    data,
    vars,
    latentVars = list(),
    modelSpec = "{\"nodes\":[],\"edges\":[]}",
    estimator = "ml",
    missing = "fiml",
    identification = "variance",
    testStats = TRUE,
    ci = FALSE,
    ciWidth = 95,
    std = FALSE,
    hideResiduals = TRUE,
    showParamTable = FALSE,
    fitChiSq = TRUE,
    fitCFI = TRUE,
    fitTLI = TRUE,
    fitSRMR = FALSE,
    fitRMSEA = TRUE,
    fitAIC = FALSE,
    fitBIC = FALSE,
    modIndices = FALSE,
    modIndicesThreshold = 3,
    residCov = FALSE,
    residCovThreshold = 0.1,
    showSyntax = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SemGui requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- SemGuiOptions$new(
        vars = vars,
        latentVars = latentVars,
        modelSpec = modelSpec,
        estimator = estimator,
        missing = missing,
        identification = identification,
        testStats = testStats,
        ci = ci,
        ciWidth = ciWidth,
        std = std,
        hideResiduals = hideResiduals,
        showParamTable = showParamTable,
        fitChiSq = fitChiSq,
        fitCFI = fitCFI,
        fitTLI = fitTLI,
        fitSRMR = fitSRMR,
        fitRMSEA = fitRMSEA,
        fitAIC = fitAIC,
        fitBIC = fitBIC,
        modIndices = modIndices,
        modIndicesThreshold = modIndicesThreshold,
        residCov = residCov,
        residCovThreshold = residCovThreshold,
        showSyntax = showSyntax)

    analysis <- SemGuiClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

